dbtsubprj2:
  outputs:
    dev:
      dataset: dmn01_rsk_cog_raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: dmn01-rsksoi-bld-01-2017
      threads: 1
      type: bigquery
  target: dev
